name: Deploy Backend Private EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend through Front EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            ssh -i /home/ec2-user/PruebaN2.pem ec2-user@10.0.6.83 << 'EOF'

            cd /home/ec2-user/app

            sudo docker compose pull

            sudo docker compose down

            sudo docker compose up -d

            EOF
